CREATE TABLE rent(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Mail NVARCHAR(100) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    Year INT NOT NULL,
    RentTime NVARCHAR(50) NOT NULL,
    Date DATETIME2 NOT NULL,
    CreateDate DATETIME2 NOT NULL DEFAULT GETDATE(),
);